package com.example.quizspark.admin.mapper;

import com.example.quizspark.admin.dto.UserDTO;
import com.example.quizspark.security.user.User;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

/**
 * MapStruct mapper interface for converting between {@link User} entities and {@link UserDTO} objects.
 * Automates the mapping process to reduce manual mapping code and improve code readability and maintainability.
 */
@Mapper
public interface UserMapper {

    /**
     * The singleton instance of {@link UserMapper}, accessible through MapStruct's {@link Mappers} factory class.
     * This instance provides the implementation generated by MapStruct at compile time.
     */
    UserMapper INSTANCE = Mappers.getMapper(UserMapper.class);

    /**
     * Converts a {@link User} entity to a {@link UserDTO}.
     *
     * @param user The {@link User} entity to be converted.
     * @return The corresponding {@link UserDTO}.
     */
    UserDTO userToUserDTO(User user);

    /**
     * Converts a {@link UserDTO} back to a {@link User} entity.
     *
     * @param userDTO The {@link UserDTO} to be converted.
     * @return The resulting {@link User} entity.
     */
    User userDTOToUser(UserDTO userDTO);
}
